#!/bin/sh
#
# Wine-loader Wrapper 
#
# The idea is to make things convenient; 
#
# - set any environment variables for wine: lpa, wine-rt, wine-staging + prefix and/or paths
# - simply starting an app from a particular node  

WINE="$1"  # Path to executable
PTH="$2"   # normally isn't used, unless you are specifying the app + a path

export WINEPREFIX="/home/ninez/winebox/node1"

export WINE_SRV_RT=${WINE_SRV_RT:-15}
export WINE_RT=${WINE_RT:-10}
export STAGING_RT_PRIORITY_SERVER=${STAGING_RT_PRIORITY_SERVER:-15}
export STAGING_RT_PRIORITY_BASE=${STAGING_RT_PRIORITY_BASE:-0}
export STAGING_SHARED_MEMORY=${STAGING_SHARED_MEMORY:-1}
export L_ENABLE_PIPE_SYNC_FOR_APP="$@"
export L_RT_POLICY="${L_RT_POLICY:-FF}"
export L_RT_PRIO=${L_RT_PRIO:-10}

exec "$WINE" "$PTH"

exit
