#!/bin/sh
echo ""
echo "------------------"
echo "Force-killing Wine" 
echo "------------------"
echo ""
killall services.exe
killall winedevice.exe
killall plugplay.exe
echo ""
echo "------------------"
echo "Killing Wineserver"
echo "------------------"
echo ""
killall -w wineserver
echo ""
echo "------------------"
echo "Wineserver is dead"
echo "------------------"
echo ""
exit
